tracks_ids_list = [
    "0V3wPSX9ygBnCm8psDIegu",
    "1bDbXMyjaUIooNwFE9wn0N",
    "3nqQXoyQOWXiESFLlDF1hG",
    "5CM4UuQ9Gnd6K2YyKGPMoK",
    "4LRPiXqCikLlN15c3yImP7",
    "46s57QULU02Voy0Kup6UEb",
    "4uUG5RXrOk84mYEfFvj3cK",
    "35ovElsgyAtQwYPYnZJECg",
    "2ZL7WZcjuYKi1KUDtp4kCC",
    "34tz0eDhGuFErIuW3q4mPX",
    "4C6Uex2ILwJi9sZXRdmqXp",
    "07aRW1pyQbQ2XyFDAuZqVj",
    "5uU1uuyaUIBOiiUSQG7Wl3",
    "7GeTsDIc5ykNB6lORO6Cee",
    "2KLwPaRDOB87XOYAT2fgxh",
    "0O6u0VJ46W86TxN9wgyqDj",
    "5IgjP7X4th6nMNDh4akUHb",
    "0hquQWY3xvYqN4qtiquniF",
    "3WMj8moIAXJhHsyLaqIIHI",
    "5jQI2r1RdgtuT8S3iG8zFC",
    "6pQr9mnsAjBlBBdFLvsgY5",
    "3cBsEDNhFI9E82vPj3kvi3",
    "4h9wh7iOZ0GGn8QVp4RAOB",
    "0wshkEEcJUQU33RSRBb5dv",
    "08De9WOIwo1VAnFDYwW8rD",
    "1E8i4Xq9tH2LVWC0b1Sptj",
    "200x8ONbPfFzByUr3fVz46",
    "3rWDp9tBPQR9z6U5YyRSK4",
    "45pUWUeEWGoSdH6UF162G8",
    "3qoftcUZaUOncvIYjFSPdE",
    "0sSRLXxknVTQDStgU1NqpY",
    "1PckUlxKqWQs3RlWXVBLw3",
    "0QHEIqNKsMoOY5urbzN48u",
    "2EjXfH91m7f8HiJN1yQg97",
    "3IpvALt7H7xQ9EyPYkektl",
    "0F3v8p8ZnEGtZDxNcJ5Klq",
    "2Lz5pso3fYgxyIF2W5oRaG",
    "72yP0DUlWPyH8P7IoxskwN",
    "4FyesJzVpA39hbYvcseO2d",
    "4D7BCuvgdJlYvlX5WlN54t",
    "1wtOxkiel43cVs0Yux5Q4h",
    "77GcYr9JP6uvJM0kPa6Nzk",
    "2ZlABhxMMa43COmZ97kKsJ",
    "1L3wDPfRVoNSwt7gXoeIkl",
    "0T5iIrXA4p5GsubkhuBIKV",
    "4Flfb4fGscN9kXPOduQLrv",
    "4686eQ81DEswHa90bcdlC9",
    "1xwAWUI6Dj0WGC3KiUPN0O",
    "1vscizuuPwkwC1cc5N5KQV",
    "1xK59OXxi2TAAAbmZK0kBL",
    "5h8IrVXuQLz4eLOdQUfEZZ",
    "1SC5rEoYDGUK4NfG82494W",
    "26hOm7dTtBi0TdpDGl141t",
    "6Tm4Io4ct4w14nB1EUzsY3",
    "2mzM4Y0Rnx2BDZqRnhQ5Q6",
    "6ug9fUi5oLLgQgOF1G8WkM",
    "24LS4lQShWyixJ0ZrJXfJ5",
    "6xGruZOHLs39ZbVccQTuPZ",
    "5JhUm1v5AbI5Yu6jLKCPRO",
    "0aV5uARAknQgYhBaK944FP",
    "2mzM4Y0Rnx2BDZqRnhQ5Q6",
    "0WtM2NBVQNNJLh6scP13H8",
    "3U21A07gAloCc4P7J8rxcn",
    "5BbdKBZO0TH0GhfxUfyhL9",
    "5JhUm1v5AbI5Yu6jLKCPRO",
    "5ZCjp56T8J6d7amJyFSzrI",
    "1QhwKZ0789eH4aE5nw0fss",
    "0Pq9K4yZlPwjjRMeIkBCpg",
    "6Y2kDIq8xmo0sYZE3o7KCE",
    "017PF4Q3l4DBUiWoXk4OWT",
    "23T0OX7QOiIUFShSzbJ5Uo",
    "3K9IrLs25jHtvWjAAFAfav",
    "5uSFGgIfHMT3osrAd9n9ym",
    "0BiqmkasE5FdrChwKfVp8X",
]


songs_name_list = [
    "Anti-Hero",
    "Rich Flex",
    "Unholy",
    "Bad Habit",
    "As It Was",
    "Major Distribution",
    "I'm Good (Blue)",
    "Lift Me Up",
    "Spin Bout U",
    "On BS",
    "Super Freaky Girl",
    "Die For You",
    "You Proof",
    "Circo Loco",
    "Pussy & Millions",
    "I Like You (A Happier Song)",
    "Under The Influence",
    "Vegas",
    "Something In The Orange",
    "Cuff It",
    "Lavender Haze",
    "Privileged Rappers",
    "Wasted On You",
    "I Ain't Worried",
    "All I Want For Christmas Is You",
    "BackOutsideBoyz",
    "Jimmy Cooks",
    "Sunroof",
    "Tomorrow 2",
    "Wait For U",
    "She Had Me At Heads Carolina",
    "Titi Me Pregunto",
    "Midnight Rain",
    "Broke Boys",
    "Bejeweled",
    "The Kind Of Love We Make",
    "Hours In Silence",
    "About Damn Time",
    "Maroon",
    "Made You Look",
    "Rockin' Around The Christmas Tree",
    "Golden Hour",
    "Thank God",
    "Unstoppable",
    "Karma",
    "Hold Me Closer",
    "Just Wanna Rock",
    "You're On Your Own, Kid",
    "Snow On The Beach",
    "Jingle Bell Rock",
    "Wait In The Truck",
    "Jumbotron Shit Poppin",
    "Half Of Me",
    "Fall In Love",
    "Shirt",
    "Until I Found You",
    "Rock And A Hard Place",
    "Treacherous Twins",
    "Hotel Lobby (Unc And Phew)",
    "What My World Spins Around",
    "Victoria’s Secret",
    "Vigilante Shit",
    "Son Of A Sinner",
    "Star Walkin' (League Of Legends Worlds Anthem)",
    "Question...?",
    "Don't Come Lookin'",
    "Middle Of The Ocean",
    "Romantic Homicide",
    "More M’s",
    "Mastermind",
    "Billie Eilish.",
    "Die For You",
    "Labyrinth",
    "Whiskey On You",
    "Free Mind",
    "California Breeze",
    "Sweet Nothing",
    "Heyy",
    "No Se Va",
    "Would've, Could've, Should've",
    "I Guess It's Fuck Me",
    "Calm Down",
    "All Mine",
    "Freestyle",
    "Country On",
    "Heart Like A Truck",
    "Miss You",
    "Wishful Drinking",
    "Music For A Sushi Restaurant",
    "Pick Me Up",
    "Break My Heart",
    "La Bachata",
    "Forever",
    "Last Last",
    "3AM On Glenwood",
    "The Great War",
    "Gotta Move On",
    "Forget Me",
    "Going, Going, Gone",
    "Bigger Than The Whole Sky",
]

artists_name_list = [
    "Taylor Swift",
    "Drake & 21 Savage",
    "Sam Smith & Kim Petras",
    "Steve Lacy",
    "Harry Styles",
    "Drake & 21 Savage",
    "David Guetta & Bebe Rexha",
    "Rihanna",
    "Drake & 21 Savage",
    "Drake & 21 Savage",
    "Nicki Minaj",
    "The Weeknd",
    "Morgan Wallen",
    "Drake & 21 Savage",
    "Drake & 21 Savage Featuring Travis Scott",
    "Post Malone Featuring Doja Cat",
    "Chris Brown",
    "Doja Cat",
    "Zach Bryan",
    "Beyonce",
    "Taylor Swift",
    "Drake & 21 Savage",
    "Morgan Wallen",
    "OneRepublic",
    "RE-\nENTRY",
    "RE-\nENTRY",
    "Mariah Carey",
    "Drake",
    "Drake Featuring 21 Savage",
    "Nicky Youre & dazy",
    "GloRilla & Cardi B",
    "Future Featuring Drake & Tems",
    "Cole Swindell",
    "Bad Bunny",
    "Taylor Swift",
    "Drake & 21 Savage",
    "Taylor Swift",
    "Luke Combs",
    "Drake & 21 Savage",
    "Lizzo",
    "Taylor Swift",
    "Meghan Trainor",
    "RE-\nENTRY",
    "RE-\nENTRY",
    "Brenda Lee",
    "JVKE",
    "Kane Brown With Katelyn Brown",
    "Sia",
    "Taylor Swift",
    "Elton John & Britney Spears",
    "Lil Uzi Vert",
    "Taylor Swift",
    "Taylor Swift Featuring Lana Del Rey",
    "RE-\nENTRY",
    "RE-\nENTRY",
    "Bobby Helms",
    "HARDY Featuring Lainey Wilson",
    "Drake",
    "Thomas Rhett Featuring Riley Green",
    "Bailey Zimmerman",
    "SZA",
    "Stephen Sanchez",
    "Bailey Zimmerman",
    "Drake & 21 Savage",
    "Quavo & Takeoff",
    "Jordan Davis",
    "Jax",
    "Taylor Swift",
    "Jelly Roll",
    "Lil Nas X",
    "Taylor Swift",
    "Jackson Dean",
    "Drake",
    "d4vd",
    "Drake & 21 Savage",
    "Taylor Swift",
    "Armani White",
    "Joji",
    "Taylor Swift",
    "Nate Smith",
    "Tems",
    "Lil Baby",
    "Taylor Swift",
    "Lil Baby",
    "Grupo Frontera",
    "Taylor Swift",
    "Drake",
    "Rema & Selena Gomez",
    "Brent Faiyaz",
    "Lil Baby",
    "Luke Bryan",
    "Lainey Wilson",
    "Oliver Tree & Robin Schulz",
    "Ingrid Andress With Sam Hunt",
    "Harry Styles",
    "Gabby Barrett",
    "Rod Wave",
    "Manuel Turizo",
    "Lil Baby Featuring Fridayy",
    "Burna Boy",
    "21 Savage",
    "Taylor Swift",
    "Diddy & Bryson Tiller",
    "RE-\nENTRY",
    "RE-\nENTRY",
    "Lewis Capaldi",
    "Luke Combs",
    "Taylor Swift",
]


